config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :users do
    get '/homepage', to: 'page#homepage'
    root to: redirect('/homepage')
    get '/add_image', to: 'users#add_image'
    put '/create_image', to: 'users#create_image'
    get '/transfer', to: 'users#transfer'
    post '/execute_transfer', to: 'users#execute_transfer'
    get '/deposite', to: 'users#deposite'
    post '/deposite_money', to: 'users#deposite_money'
    get '/upload_avatar', to: 'avatar#edit'
    put '/upload_avatar', to: 'avatar#update'
    delete '/delete_avatar', to: 'avatar#destroy'

    resources :set_pin, only: %i[edit update]
    resources :account_histories, only: [:index]
  end
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
  belongs_to :accountable, polymorphic: true

  def self.ransackable_associations(auth_object = nil)
    ["accountable"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["accountable_id", "accountable_type", "created_at", "final_balance", "id", "id_value", "initial_balance", "transaction_history", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :account_histories, as: :accountable
  enum status: {
    active: 'active',
    inactive: 'inactive',
    archived: 'archived'
  }
  has_one_attached :image

  validates :pin_number, length: { is: 4 }, if: -> { pin_number.present? }
  validates :name, presence: true, length: { minimum: 2 },
            format: { with: /[a-zA-Z]+/, message: 'Only letters allowed' }
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 80 }
  validates :date_of_birth, comparison: { less_than_or_equal_to: Date.today }
  before_create  :set_account_number
  before_create :set_balance

  private 

  def set_account_number
    # debugger
    self.account_number = rand.to_s[2..6].to_i
  end

  def set_balance
    self.balance = 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :user_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource.role
    when 'user'
      users_homepage_path
    else
      super
    end
  end

  protected

  def user_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email age date_of_birth role])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email age date_of_birth role])
 end

end

app/controllers/users/account_histories_controller.rb
class Users::AccountHistoriesController < Users::UsersController
  def index
    # @history = current_user.account_histories.all.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    @q = current_user.account_histories.ransack(params[:q])
    @history = @q.result.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/users/avatar_controller.rb
class Users::AvatarController < Users::UsersController
  def edit 
  end

  def update
    current_user.image.attach(params[:image])
    redirect_to users_upload_avatar_path, success: 'Uoploaded successfullyt'
  end

  def destroy
  end
end

app/controllers/users/page_controller.rb
class Users::PageController < Users::UsersController 
  def homepage
  end
end

app/controllers/users/set_pin_controller.rb
class Users::SetPinController < Users::UsersController

  def edit
  end

  def update
    if current_user.update(pin_params)
      flash[:notice] = 'Updated successfully'
    else
      flash[:alert] = current_user.errors.full_messages
    end
    redirect_to edit_users_set_pin_path
  end
  private
  def pin_params
    params.require(:user).permit(:pin_number)
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ammount, only: %i[execute_transfer deposite_money]
  before_action :set_to_account_number, only: %i[execute_transfer]
  
  def create_image
  end

  def execute_transfer
    if current_user.balance < @ammount
      return redirect_to users_transfer_path, alert: 'Low balance'
    end
    @sender_initial_balance = current_balance(current_user)
    @reciever_initial_balance = current_balance(@to_user)
    credited_ammount = @reciever_initial_balance + @ammount
    debited_ammount = @sender_initial_balance - @ammount

    if @to_user.update(balance: credited_ammount) && current_user.update(balance: debited_ammount)
      # update the sneder history
      sender_account_history = current_user.account_histories.new
      sender_account_history.initial_balance = @sender_initial_balance
      sender_account_history.transaction_history = "Rs.#{@ammount} send to #{@to_user.name}"
      sender_account_history.final_balance = current_balance(current_user)
      sender_account_history.save

      # update the reciever history
      reciever_account_history = @to_user.account_histories.new
      reciever_account_history.initial_balance = @reciever_initial_balance
      reciever_account_history.transaction_history = "Rs.#{@ammount} recieved from #{current_user.name}"
      reciever_account_history.final_balance = current_balance(@to_user)
      reciever_account_history.save

      redirect_to users_root_path, notice: 'Sent successfully'
    end
  end

  # get method for deposte
  def deposite
  end

  # post method for deposite 
  def deposite_money
    # debugger  
    @initial_balance = current_balance(current_user)
    @final_ammount = @initial_balance + @ammount
    if current_user.update(balance: @final_ammount)
      # update current user account history
      history = current_user.account_histories.new
      history.initial_balance = @initial_balance
      statement = "Rs.#{@ammount} deposited to #{current_user.name}"
      history.final_balance = @final_ammount.to_i
      history.transaction_history = statement.to_s
      history.save
      UserMailer.with(
        deposite_ammount: @ammount,
        user: current_user
      ).money_deposite.deliver_now
    end
    redirect_to users_root_path, notice: 'Deposited successfully!!'
  end

  private 

  def set_ammount
    @ammount = params[:ammount].to_i
    flash[:alert] = 'invalid ammount' if @ammount <= 0
    if flash[:alert].present?
      if request.referer.include? '/users/deposite'
        redirect_to users_deposite_path
      elsif request.referer.include? '/users/transfer'
        redirect_to users_transfer_path
      end
    end
  end

  def set_to_account_number
    all_account_number = User.pluck(:account_number)
    unless all_account_number.include? params[:to_account_number].to_i
      return redirect_to users_transfer_path, alert: 'Invalid account number'
    end
    @to_user = User.find_by(account_number: params[:to_account_number])
  end

  def current_balance user_account
    return user_account.balance.to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Hdfc
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .notice= notice
    .alert= alert
    = yield

app/views/users/account_histories/index.html.haml
= search_form_for @q, url: users_account_histories_path do |f|
  = f.label :transaction
  = f.text_field :transaction_history_cont

  = f.submit 'Search'
%table.table.table-hover.table-striped.table-secondary.table-responsive.table-bordered.text-black
  %thead.table-dark
    %tr
      %th Initial balance
      %th Transaction
      %th Final balance
  %tbody.table-group-divider
    - @history.each do |hist|
      %tr
        %td= hist.initial_balance
        %td= hist.transaction_history
        %td= hist.final_balance

= will_paginate @history, class: 'digg_pagination'

app/views/users/avatar/edit.html.haml
.div{style: 'background-color: pink; height: 300px; width: 300px'}
  - if current_user.image.attached?
    = image_tag(current_user.image, style: 'height: 200px; width: 200px; border-radius: 50%; margin: 10%; margin-left: 20%')
= form_with model: @avatar, url: users_upload_avatar_path, method: :put do |f|

  = f.label :image
  = f.file_field :image

  = f.submit 'Upload'

app/views/users/page/homepage.html.haml
%p.text-black hello to 
= current_user.name
= "account number is #{current_user.account_number} and balance is Rs.#{current_user.balance}"
- if user_signed_in?
  .d-flex.gap-3
    = button_to 'Logout ', destroy_user_session_path, method: :delete,class: 'btn btn-primary'
    = link_to 'Send money', users_transfer_path, class: 'btn btn-primary'
    = link_to 'Top up money', users_deposite_path, class: 'btn btn-primary'
    = link_to 'Account history', users_account_histories_path, class: 'btn btn-primary' 
    = link_to 'Set pin', edit_users_set_pin_path(current_user), class: 'btn btn-primary'

app/views/users/set_pin/edit.html.haml
= form_with model: current_user, url: users_set_pin_path(current_user), method: :patch do |f|
  = f.label :pin_number
  = f.number_field :pin_number

  = f.submit 'Set pin', class: 'btn btn-success'

app/views/users/shared/_error_messages.html.haml
rails active_storage:install- if resource.errors.any?
  #error_explanation{"data-turbo-cache" => "false"}
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/users/add_image.html.haml
wlcom to images 

= form_with model: @image, url: users_create_image_path, method: :put do |f|
  = f.label :images
  = f.file_field :images,  multiple: true

  = f.submit

app/views/users/users/deposite.html.haml
Depoiste Money

= form_with url: users_deposite_money_path, method: :post do |f|
  = f.label :ammount
  = f.number_field :ammount, autocomplete: 'off'

  = f.submit 'Deposite!', class: 'btn btn-primary'

app/views/users/users/transfer.html.haml
hello to transfer 

= form_with url: users_execute_transfer_path, method: :post, local: true do |f|
  = f.label :to_account_number
  = f.number_field :to_account_number, autocomplete: 'off'

  = f.label :ammount
  = f.number_field :ammount, autocomplete: 'off'

  = f.submit